blank_issues_enabled: true
contact_links:
  - name: ğŸ’¡ Feature request
    url: https://discuss.shipyard.khulnasoft.com/
  - name: â“ Question
    url: https://discuss.shipyard.khulnasoft.com
    about: Ask a question about Shipyard
  - name: ğŸ“–  Shipyard Documentation
    url: https://shipyard.khulnasoft.com/docs/getting-started/overview/
    about: The Shipyard documentation may answer your questions!
  - name: ğŸ’¬  Shipyard Community Support (Slack)
    url: https://shipyard-community.slack.com
    about: Please ask and answer questions here.
